services:
  # === FRONTEND (React) ===
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sires-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:5000/api/v1
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - sires-network

  # === BACKEND (Flask) ===
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sires-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      TZ: "America/Mexico_City"
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_started
    networks:
      - sires-network

  # === REDIS (Base de datos OTP) ===
  redis:
    image: redis:7-alpine
    container_name: sires-redis
    ports:
      - "6379:6379"
    networks:
      - sires-network

# Red interna
networks:
  sires-network:
    driver: bridge
